name: Continuous deployment


on:
  push:
    branches: [main]
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  create-version-pr-or-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Create version PR or Github Releease
        id: changeset
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: $${{ secrets.CHANGESETS_TOKEN }}
      - run: echo '${{ toJson(steps.changeset.outputs)}}'
      - name: Send a slack message for a slack message
        if: steps.changeset.outputs.pullRequestNumber
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn"
                            "text": "🤏 *<https://github.com/${{github.repository}}/pull/${{steps.changeset.outputs.pullRequestNumber }}|Version Pull Request>* was
                             updated. Review it and merge it to create a new release and deployment"
                        }
                    }
                ]
            }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

